# Generated by Django 2.0.13 on 2020-07-07 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("users", "0058_auto_20200615_2030")]

    operations = [
        migrations.AlterField(
            model_name="authorization",
            name="partners",
            field=models.ManyToManyField(
                blank=True,
                help_text="The partner(s) for which the editor is authorized.",
                limit_choices_to=models.Q(status__in=[0, 2]),
                to="resources.Partner",
            ),
        ),
        migrations.AlterField(
            model_name="authorization",
            name="stream",
            field=models.ForeignKey(
                blank=True,
                help_text="The stream for which the editor is authorized.",
                limit_choices_to=models.Q(partner__status__in=[0, 2]),
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="resources.Stream",
            ),
        ),
    ]
